name: 🐛 Bug Report
description: Create a bug report to help us improve
title: "[BUG] <brief description>"
labels: [bug]
body:
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug you encountered...
    validations:
      required: true
      
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
      
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
      placeholder: |
        - OS: [e.g. Windows 10, macOS 12.0, Ubuntu 20.04]
        - Browser: [e.g. Chrome 95, Safari 15, Firefox 94]
        - Device: [e.g. Desktop, Mobile, Tablet]
        - Version: [e.g. v1.0.0]
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Screen Recordings
      description: If applicable, add screenshots or screen recordings to help explain your problem
    validations:
      required: false
      
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve TechRosie! 🌹
        
        Our team will review your bug report and get back to you as soon as possible.
