blank_issues_enabled: false
contact_links:
  - name: 🌹 TechRosie Organization
    url: https://github.com/TechRosie
    about: Visit our main organization page
  - name: 💬 Community Discussions
    url: https://github.com/TechRosie/femtracker/discussions
    about: Join community discussions and get help
