// Read what the YouTube channel publicly shows and write youtube/videos.yaml.
//
// youtube/channel.yaml is the curated register (kind, project, playlists, the
// decisions). This file is the other half: the title and the full description
// of every PUBLIC video and Short, exactly as a signed-out visitor gets them,
// so a description can be read, diffed and rewritten without opening Studio.
// Unlisted and private videos are invisible to it by construction.
//
//   node scripts/capture-youtube.mjs
//
// Needs yt-dlp (on PATH, or YT_DLP=<path>, or D:\yt-dlp\yt-dlp.exe) and the
// network, so it is not part of `npm run build` or `npm run check`. It ends by
// listing ids that are public on YouTube but missing from channel.yaml, and
// the other way round. Views keep their historical maximum.

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(repoRoot, "youtube", "videos.yaml");
const REGISTER = path.join(repoRoot, "youtube", "channel.yaml");
const CHANNEL = "https://www.youtube.com/@ChanMeng666";

const bin = process.env.YT_DLP
  ?? (fs.existsSync("D:/yt-dlp/yt-dlp.exe") ? "D:/yt-dlp/yt-dlp.exe" : "yt-dlp");
const ytdlp = (args) =>
  execFileSync(bin, ["--no-warnings", "--encoding", "utf-8", ...args], { encoding: "utf8", maxBuffer: 1 << 28 });

const idsOf = (tab) =>
  ytdlp(["--flat-playlist", "--print", "%(id)s", `${CHANNEL}/${tab}`]).split(/\r?\n/).filter(Boolean);

const tabs = { videos: idsOf("videos"), shorts: idsOf("shorts") };
const previous = fs.existsSync(OUT) ? yaml.load(fs.readFileSync(OUT, "utf8")) : null;
const oldViews = new Map((previous?.videos ?? []).map((v) => [v.id, v.views ?? 0]));

const videos = [];
for (const [tab, ids] of Object.entries(tabs)) {
  for (const id of ids) {
    const j = JSON.parse(ytdlp([
      "--skip-download", "--ignore-no-formats-error",
      "--print", "%(.{id,title,description,duration,upload_date,view_count})j",
      `https://www.youtube.com/watch?v=${id}`,
    ]));
    const d = j.upload_date ?? "";
    videos.push({
      id,
      tab,
      title: j.title,
      uploadedUtc: d ? `${d.slice(0, 4)}-${d.slice(4, 6)}-${d.slice(6, 8)}` : null,
      seconds: j.duration,
      views: Math.max(j.view_count ?? 0, oldViews.get(id) ?? 0),
      links: [...new Set((j.description ?? "").match(/https?:\/\/[^\s)]+/g) ?? [])],
      description: (j.description ?? "").replace(/\r\n/g, "\n").trim(),
    });
  }
}

const header = `# =============================================================================
# YouTube public videos — @ChanMeng666 — titles and descriptions as published
# =============================================================================
# GENERATED by \`npm run capture:youtube\` (scripts/capture-youtube.mjs) from the
# public channel pages: do not hand-edit. To change a title or a description,
# change it in YouTube Studio (youtube/README.md says how), then capture again.
# The curated half (kind, project, playlists, decisions) is channel.yaml.
# Public videos and Shorts only. \`uploadedUtc\` is YouTube's UTC date, which can
# be one day behind the Auckland date in channel.yaml. \`views\` never goes down.
# =============================================================================

`;
const body = yaml.dump(
  { asOf: new Date().toISOString().slice(0, 10), counts: { videos: tabs.videos.length, shorts: tabs.shorts.length }, videos },
  { lineWidth: -1, noRefs: true },
);
fs.writeFileSync(OUT, header + body);
console.log(`capture-youtube: ${videos.length} public videos → youtube/videos.yaml`);

const register = yaml.load(fs.readFileSync(REGISTER, "utf8"));
const registered = new Set((register.videos ?? []).map((v) => v.id));
const live = new Set(videos.map((v) => v.id));
const unregistered = [...live].filter((id) => !registered.has(id));
const gone = [...registered].filter((id) => !live.has(id));
if (unregistered.length) console.log(`  public but not in channel.yaml: ${unregistered.join(", ")}`);
if (gone.length) console.log(`  in channel.yaml but no longer public: ${gone.join(", ")}`);
const bare = videos.filter((v) => !v.links.length).map((v) => v.id);
if (bare.length) console.log(`  descriptions with no link: ${bare.join(", ")}`);
if (unregistered.length || gone.length) process.exitCode = 1;
