name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # 每天运行一次
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ChanMeng666
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Pacific/Auckland
          
          # 个性化统计内容
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          plugin_stargazers: yes
          plugin_stargazers_charts_type: classic
          
          plugin_people: yes
          plugin_people_types: followers, following
          
          plugin_calendar: yes
          plugin_calendar_limit: 14
          plugin_calendar_from: 2023 